; Sonic 1 Github
obRender:		equ ost_render
obGfx:			equ ost_tile
obMap:			equ ost_mappings
obX:			equ ost_x_pos
obScreenY:		equ ost_y_screen
obY:			equ ost_y_pos
obVelX:			equ ost_x_vel
obVelY:			equ ost_y_vel
obInertia:		equ ost_inertia
obWidth:		equ ost_width
obHeight:		equ ost_height
obPriority:		equ ost_priority
obActWid:		equ ost_actwidth
obFrame:		equ ost_frame
obAniFrame:		equ ost_anim_frame
obAnim:			equ ost_anim
obNextAni:		equ ost_anim_restart
obTimeFrame:		equ ost_anim_time
obDelayAni:		equ ost_anim_delay
obColType:		equ ost_col_type
obColProp:		equ ost_col_property
obStatus:		equ ost_status
obRespawnNo:		equ ost_respawn
obRoutine:		equ ost_routine
ob2ndRout:		equ ost_routine2
obAngle:		equ ost_angle
obSubtype:		equ ost_subtype
obSolid:		equ ost_solid

; Sonic 2 Github
id:			equ ost_id
render_flags:		equ ost_render
art_tile:		equ ost_tile
mappings:		equ ost_mappings
x_pos:			equ ost_x_pos
x_sub:			equ ost_x_sub
y_pos:			equ ost_y_pos
y_sub:			equ ost_y_sub
priority:		equ ost_priority
width_pixels:		equ ost_actwidth
mapping_frame:		equ ost_frame
x_vel:			equ ost_x_vel
y_vel:			equ ost_y_vel
y_radius:		equ ost_height
x_radius:		equ ost_width
anim_frame:		equ ost_anim_frame
anim:			equ ost_anim
prev_anim:		equ ost_anim_restart
anim_frame_duration:	equ ost_anim_time
status:			equ ost_status
routine:		equ ost_routine
routine_secondary:	equ ost_routine2
angle:			equ ost_angle
collision_flags:	equ ost_col_type
collision_property:	equ ost_col_property
respawn_index:		equ ost_respawn
subtype:		equ ost_subtype
inertia:		equ ost_inertia
flip_angle:		equ ost_angle+1
air_left:		equ ost_subtype
flip_turned:		equ $29
obj_control:		equ $2A
status_secondary:	equ $2B
flips_remaining:	equ $2C
flip_speed:		equ $2D
move_lock:		equ $2E
invulnerable_time:	equ ost_sonic_flash_time
invincibility_time:	equ ost_sonic_inv_time
speedshoes_time:	equ ost_sonic_shoe_time
next_tilt:		equ ost_sonic_angle_right
tilt:			equ ost_sonic_angle_left
stick_to_convex:	equ ost_sonic_sbz_disc
spindash_flag:		equ $39
pinball_mode:		equ spindash_flag
spindash_counter:	equ ost_sonic_restart_time
restart_countdown:	equ ost_sonic_restart_time
jumping:		equ ost_sonic_jump
interact:		equ ost_sonic_on_obj
top_solid_bit:		equ $3E
lrb_solid_bit:		equ $3F
y_pixel:		equ ost_y_screen
x_pixel:		equ ost_x_pos
parent:			equ $3E
button_up:		equ bitUp
button_down:		equ bitDn
button_left:		equ bitL
button_right:		equ bitR
button_B:		equ bitB
button_C:		equ bitC
button_A:		equ bitA
button_start:		equ bitStart
button_up_mask:		equ btnUp
button_down_mask:	equ btnDn
button_left_mask:	equ btnL
button_right_mask:	equ btnR
button_B_mask:		equ btnB
button_C_mask:		equ btnC
button_A_mask:		equ btnA
button_start_mask:	equ btnStart